"""empty message

Revision ID: 6bbe7150a0f9
Revises: a83df9ac0d52
Create Date: 2017-05-17 11:31:44.304992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe7150a0f9'
down_revision = 'a83df9ac0d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
