"""empty message

Revision ID: a83df9ac0d52
Revises: c75cdd185545
Create Date: 2017-05-17 11:26:29.765458

"""
from alembic import op
import sqlalchemy as sa
from gefapi.models import GUID


# revision identifiers, used by Alembic.
revision = 'a83df9ac0d52'
down_revision = 'c75cdd185545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('user_id', GUID(), nullable=True))
    op.create_foreign_key(None, 'execution', 'user', ['user_id'], ['id'])
    op.add_column('script', sa.Column('public', sa.Boolean(), nullable=True))
    op.alter_column('script', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('script', 'public')
    op.drop_constraint(None, 'execution', type_='foreignkey')
    op.drop_column('execution', 'user_id')
    # ### end Alembic commands ###
