"""Add description column in script

Revision ID: c75cdd185545
Revises: 9eb257aebbe6
Create Date: 2017-04-27 10:17:16.360328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75cdd185545'
down_revision = '9eb257aebbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script', 'description')
    # ### end Alembic commands ###
