"""Change type of id in execution_log

Revision ID: e667092daec1
Revises: 9eb257aebbe6
Create Date: 2017-04-05 13:48:11.473012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e667092daec1'
down_revision = '9eb257aebbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_log', 'id')
    op.add_column('execution_log', sa.Column('id', sa.Integer(), nullable=False))    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_log', 'id')
    op.add_column('execution_log', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))    
    # ### end Alembic commands ###
